ignore null values in sequelize storage
sequelize/umzug pull request #323
Opened 2020-09-19 17:16 UTC by luwol03

Hello guys,

I like umzug a lot. But I get this error.
![image](https://user-images.githubusercontent.com/60048565/93673908-b9b1a480-faab-11ea-8c45-fdf6b91ea560.png)
After a lot of time I figgerd out, that I can't use a table like that to compress the migrations and seeders into one:
```sql
CREATE TABLE ".migrations" (
	"id"	INTEGER,
	"migrations"	VARCHAR(255),
	"seeders"	VARCHAR(255),
	"createdAt"	DATETIME NOT NULL,
	"updatedAt"	DATETIME NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
```
I think it would be a good idea to reduce the array insted of map it and throw an error if it isn't a string.

I'm not so familar with typescript. If there are types missing please add it.

2020-09-19 18:38 UTC, mmkal requested changes
Comments on the code left inline.

More generally: does this make sense to do? Do we really want to silently filter out migrations instead of throwing? For sure, something is wrong since you're getting unhandled rejections, but I don't think it's wrong _here_.

2020-09-19 18:38 UTC, mmkal commented on src/storage/sequelize.ts
> +			return migrations;
`reduce` is usually for avoiding mutating arrays, doesn't make much difference in this case but in general better practice to do `return [... migrations, name]` here.

2020-09-19 18:38 UTC, mmkal commented on src/storage/sequelize.ts
> +		return migrations.reduce((migrations, migration) => {
Let's not shadow the `migrations` variable. In fact, the linter should protect us from this. Will check why it's not soon.

2020-09-19 18:38 UTC, mmkal commented on src/storage/sequelize.ts
> +		}, []);
Can we change `[]` to `[] as string []`?

2020-09-19 18:38 UTC, mmkal commented on src/storage/sequelize.ts
> +				return migrations;
Isn't doing this the equivalent of a using `.filter` before `.map`?

2020-09-19 18:42 UTC, luwol03 commented
Year, you are right with the last points. Filter is a better way to handle it.

2020-10-03 07:52 UTC, luwol03 commented
Hello, are there any updates, because i am very fustrated, now, if this wont be merged, i have tried to use 2 different table names, but always both **new** `SequelizeStorage` instaces uses the same sql table.

2020-10-03 13:57 UTC, mmkal commented
@luwol03 as I mentioned before, I'm not convinced ignoring invalid values is a better idea than throwing. Your new approach of a separate umzug instance for seeders makes sense to me.

About seeders going in the wrong table: it's likely because the sequelize storage only creates a table if the model doesn't already exist. Try replacing `tableName` with `modelName` in both umzug constructors.

2020-10-03 18:38 UTC, closed without merging

2020-10-04 20:54 UTC, luwol03 commented
Ok, thank you with model name it works great..