docs: add example for multiple glob dirs
sequelize/umzug pull request #343
Opened 2020-10-07 17:16 UTC by mmkal

2020-10-07 17:49 UTC, papb reviewed
Can you please remind me how are the migrations ordered by default in this case? Is it lexicographically ascending on the file names directly, or first on the folder names and then file names?

2020-10-07 18:42 UTC, mmkal commented
@papb good call-out, I added a section to the docs.

2020-10-11 03:53 UTC, papb requested changes

2020-10-11 03:53 UTC, papb commented on README.md
> +- file matches, found using [glob](https://npmjs.com/package/glob), will be alphabetically sorted based on their paths
```suggestion
- file matches, found using [glob](https://npmjs.com/package/glob), will be lexicographically sorted based on their paths
```

2020-10-11 03:53 UTC, papb commented on README.md
> +- The easiest way to deal with this is to ensure your migrations appear in a single folder, and their paths match alphabetically with the order they should run in
```suggestion
- The easiest way to deal with this is to ensure your migrations appear in a single folder, and their paths match lexicographically with the order they should run in
```

2020-10-11 12:32 UTC, merged