docs: clarify that up and down functions don't take parameters
sequelize/umzug pull request #355
Opened 2020-10-14 22:55 UTC by mmkal

To make things as clear as possible, I've replaced all `spy.bind(null, blah)` calls with `async () => spy(blah)`, which makes it more explicit that no parameters are expected. This also adds a test to make sure that both the type system and runtime agree that no parameters are expected.

This will need to merge from master after #354 goes in as there'll be a "soft" merge conflict in the new test.

Note that the default resolver does pass parameters to the up and down functions of file-migrations, though. Example: https://github.com/sequelize/umzug/blob/153cda4eca2914a94f65b73548953a5bcfd6adde/test/umzug.test.ts#L24-L35

2020-10-15 01:14 UTC, papb commented
Hmmm, somehow I missed this difference. I don't like the fact that the signatures of the `up` and `down` functions are different when they were created by a custom resolver versus the default. This also means that the "trivial" resolver `x => x` actually breaks it all then?

2020-10-15 01:20 UTC, papb reviewed
Hmmm, somehow I missed this difference. I don't like the fact that the signatures of the `up` and `down` functions are different when they were created by a custom resolver versus the default. This also means that the "trivial" resolver `({ path }) => require(path)` actually doesn't work then?

I think `up` and `down` functions should always receive `{ name, path, context }`. But maybe I'm biased by the fact that I took this for granted subconsiously since the beginning :sweat_smile: is there any reason to not pass them?

Edit: now that I think of it I also don't know why the resolver receives `context`, but I don't mind that, it can't hurt, maybe it would be useful in some situation.

2020-10-15 12:41 UTC, mmkal commented
@papb you're, right the user experience works be better if you didn't need to remember the difference between a migration file and a migration object. And I can't think of the top of my head why it _wouldn't_ be possible. I'll try it out in this PR.

2020-10-22 19:36 UTC, papb requested changes
Nice!!

2020-10-22 19:36 UTC, papb commented on test/umzug.test.ts
> +	test('up and down functions should not take parameters', async () => {
```suggestion
	test('resolved up and down functions should take the usual parameters', async () => {
```

2020-10-22 19:36 UTC, papb commented on test/umzug.test.ts
> +		expect(spy).toHaveBeenNthCalledWith(1, 'up', 'migration1.sql', 'migration1.sql');
Can you also spy and test for `.path` and `.context`, instead of just checking `.name`?

2020-10-27 14:29 UTC, merged